package examples;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

/**
 * A typical Lombok class. Because it carries {@code @Builder}, the plugin offers conversions on
 * any constructor or setter usage of it. {@code @AllArgsConstructor}/{@code @NoArgsConstructor}
 * would normally be generated by Lombok; they are written out here so the example compiles on its
 * own.
 */
@Getter
@Setter
@Builder
public class User {
    private Long id;
    private String name;
    private String email;
    private boolean active;

    public User() {}

    public User(Long id, String name, String email, boolean active) {
        this.id = id;
        this.name = name;
        this.email = email;
        this.active = active;
    }

    public void setId(Long id) { this.id = id; }
    public void setName(String name) { this.name = name; }
    public void setEmail(String email) { this.email = email; }
    public void setActive(boolean active) { this.active = active; }
}
